// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lablinAPI.Models;

public partial class tbl_ngs_run_info
{
    public int id { get; set; }

    public int? runID { get; set; }

    public string runInfo { get; set; }
}