// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lablinAPI.Models;

public partial class tbl_project_files
{
    public int ID { get; set; }

    public int? projectID { get; set; }

    public string filePath { get; set; }

    public DateTime? createdDateTime { get; set; }

    public string fileType { get; set; }
}