// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lablinAPI.Models;

public partial class tbl_sample
{
    public int id { get; set; }

    public int? sampleSubmissionSheetID { get; set; }

    public string medGenID { get; set; }

    public string sampleName { get; set; }

    public string batchDescription { get; set; }

    public int? batchNumber { get; set; }

    public string replicateDescription { get; set; }

    public string technicalReplicateNumber { get; set; }

    public string experimentalGroup { get; set; }

    public int? replicate { get; set; }

    public string condition { get; set; }

    public string species { get; set; }

    public string qualityOfLibrary { get; set; }

    public string parentalLine { get; set; }

    public string donorType { get; set; }

    public string cellType { get; set; }

    public string notes { get; set; }

    public string raw_data { get; set; }

    public string analysis { get; set; }

    public string analysisType { get; set; }

    public DateTime? createdDateTime { get; set; }
}