// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lablinAPI.Models;

public partial class tbl_project_users
{
    public int ID { get; set; }

    public int? projectID { get; set; }

    public int? userID { get; set; }
}