// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lablinAPI.Models;

public partial class tbl_project
{
    public int id { get; set; }

    public DateOnly? created_timestamp { get; set; }

    public string project_number { get; set; }

    public string project_name { get; set; }

    public int? year { get; set; }

    public string sample_info { get; set; }

    public DateTime? date_of_submission { get; set; }

    public int? sequencing_depth { get; set; }

    public string length { get; set; }

    public bool? paired { get; set; }
}