// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lablinAPI.Models;

public partial class tbl_flowcell
{
    public int id { get; set; }

    public string name { get; set; }
}