// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lablinAPI.Models;

public partial class tec_project_samples
{
    public int id { get; set; }

    public int? projectID { get; set; }

    public int? sampleID { get; set; }
}